# Generated by Django 2.2.16 on 2021-01-06 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='answer',
        ),
    ]
