# Generated by Django 2.2.16 on 2020-12-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
