# Generated by Django 2.2.16 on 2020-12-13 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='answer',
            field=models.CharField(default='', max_length=500),
        ),
    ]
