# Generated by Django 2.2.16 on 2021-01-05 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0002_question_test'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('UserID', 'answer')},
        ),
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('question', 'choice_text', 'correct')},
        ),
        migrations.AlterModelOptions(
            name='totalscore',
            options={'ordering': ('User', 'test', 'section', 'score')},
        ),
        migrations.AddField(
            model_name='answer',
            name='section',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SAT.Section'),
        ),
        migrations.AddField(
            model_name='answer',
            name='test',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SAT.Test'),
        ),
    ]
