# Generated by Django 2.2.16 on 2021-01-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0002_remove_choice_answer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='section',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='test',
        ),
    ]
