# Generated by Django 2.2.16 on 2021-01-06 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SAT', '0003_auto_20210106_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='SAT.Choice'),
        ),
    ]
